config/routes.rb
Yenta::Application.routes.draw do

  get "admin" => "admin#index", as: :user_root
  get "admin/bookings" => "admin#bookings", as: :admin_bookings
  get "admin/enquires" => "admin#enquires", as: :admin_enquires
  devise_for :users, :controllers => { :sessions => 'sessions' }
  resources :bookings

  resources :enquires

  get "contact/index"
  get "health_check/index"
  get "home/index"
  get "who-we-are" => "static#wwr", as: :who_we_are
  get "what-we-do" => "static#wwd", as: :what_we_do
  get "privacy" => "static#privacy", as: :privacy
  get "copyright" => "static#copyright", as: :copyright
  
  get "contact_us" => "contact#index", as: :contact_us
  
  post "create_enquire" => "contact#create_enquire", as: :create_enquire
  post "create_booking" => "contact#create_booking", as: :create_booking
  root 'home#index'

  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, email: true
  # validates :from, presence: true
  # validates :to, presence: true
  # validates :date_of_departure, presence: true
  # validates :date_of_return, presence: true
  validates :number_of_passangers, presence: true, numericality: { only_integer: true }

  has_many :multi_stopovers   
  accepts_nested_attributes_for :multi_stopovers
  before_save :remove_empty_multi_stipovers
  
  TRAVEL_TYPE_ONE_WAY = "one way"
  TRAVEL_TYPE_RETURN = "return"
  TRAVEL_TYPE_MULTI = "multi stopover"
  
  def remove_empty_multi_stipovers
    if self.travel_type == TRAVEL_TYPE_MULTI
      self.multi_stopovers = self.multi_stopovers.delete_if {|obj| obj.from.blank? && obj.to.blank? && obj.date.blank?}      
    end
    return true;
  end
  
end

app/models/enquire.rb
class Enquire < ActiveRecord::Base
  #attr_accessible  :first_name, :email, :message
  
  validates :first_name, presence: true
  validates :email, presence: true, email: true
  
end

app/models/iso_country.rb
class IsoCountry < ActiveRecord::Base
  scope :country_names, order("id")
end

app/models/multi_stopover.rb
class MultiStopover < ActiveRecord::Base
  belongs_to :booking
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
   layout "admin"
  before_filter :authenticate_user!
  
  def index
    @ba = Booking.all.size
    @ea = Enquire.all.size
  end
  
  def enquires
    @entries = Enquire.all
  end
  
  def bookings
    @bookings = Booking.all
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  layout "static"
  before_filter :init_objects  
  BOOKING_FLASH = "Your booking has been send to us!"
  def new
    3.times { @booking.multi_stopovers.build} if @booking.multi_stopovers.size == 0
    showhideform()
  end
  
  def create
    if (@booking.update_attributes(booking_params))
      NoticeMailer.booking_email(@booking).deliver
      flash[:notice] = BOOKING_FLASH
      redirect_to action: :new
      return
    end
    showhideform()
    render "new"
  end
  
  def booking_params
    params.require(:booking).permit(:first_name, :last_name, :travel_type, :seat_class, :email, :from, :to, :date_of_departure, :date_of_return, :number_of_passangers, multi_stopovers_attributes:[:from, :to, :date])
  end  
  
  def showhideform()
    if @booking.travel_type == Booking::TRAVEL_TYPE_MULTI
      @multi_stepover = ""
      @return_form =  "display:none"      
    elsif @booking.travel_type == Booking::TRAVEL_TYPE_ONE_WAY
      @single_form = "display:none"
    end    
  end
  
  def init_objects
    @booking = Booking.new 
    @booking.travel_type = Booking::TRAVEL_TYPE_RETURN  
    @return_form = ""
    @single_form = ""
    @multi_stepover = "display:none"
         
  end
  
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  layout "static"
  before_filter :init_objects
  BOOKING_FLASH = "Your booking has been send to us!"
  ENQUIRE_FLASH = "Your enquire has been send to us!"
  
  def index
  end
  
  def create_enquire
    if (@enquire.update_attributes(enquire_params))
      NoticeMailer.enquire_email(@enquire).deliver
      flash[:notice] = ENQUIRE_FLASH
      redirect_to action: :index
      return
    else
      @hide_enquire_form = false      
    end
    render "index"
  end
  
  def create_booking
    if (@booking.update_attributes(booking_params))
      NoticeMailer.booking_email(@booking).deliver
      flash[:notice] = BOOKING_FLASH
      redirect_to action: :index
      return
    else
      @hide_booking_form = false      
    end
    render "index"
  end
  
  
 private
  def init_objects
    @enquire = Enquire.new
    @booking = Booking.new
    @hide_enquire_form = true
    @hide_booking_form = true  
  end
  
  def enquire_params
    params.require(:enquire).permit(:first_name, :email, :message)
  end
  
  def booking_params
    params.require(:booking).permit(:first_name, :surname, :place_of_origin, :email, :phone, :accept_call, :message)
  end  

end

app/controllers/enquires_controller.rb
class EnquiresController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
   layout "empty"   
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout "static"
  
  def wwr
  end
  
  def wwd
  end
  
  def privacy
  end
  
  def copyright
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_background_images
    images=["background-1d.jpg","background-2d.jpg","background-3d.jpg","background-4d.jpg","background-5d.jpg"]
    index = rand(0..(images.size - 1))
    return images[index]  
  end
    
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/enquires_helper.rb
module EnquiresHelper
end

app/helpers/health_check_helper.rb
module HealthCheckHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper  
end

app/views/admin/_header.html.haml
.navbar.navbar-inverse.navbar-fix-top{"role"=>"navigation"}
  .container
    .navbar-header
      = link_to "Yenta", "/", class:"navbar-brand"
    .navbar-collapse.collapse
      %ul.nav.navbar-nav      
        -if action?("index")
          %li.active
            = link_to "Dashboard", user_root_path     
        -else
          %li
            = link_to "Dashboard", user_root_path 
        -if action?("bookings")
          %li.active
            = link_to "Bookings", admin_bookings_path                            
        -else
          %li
            = link_to "Bookings", admin_bookings_path
        -if action?("enquires")
          %li.active
            = link_to "Enquires", admin_enquires_path
        -else          
          %li
            = link_to "Enquires", admin_enquires_path
      .logout.pull-right
        = link_to('Logout', destroy_user_session_path, :method => :delete)
        

app/views/admin/bookings.html.haml
%h3
  Total:
  =@bookings.size
%table.table.table-striped.table-hover
  %tr
    %th
      first_name
    %th
      surname
    %th
      place_of_origin
    %th
      email
    %th
      accept_call
    %th
      phone
    %th
      message
    %th
      created at
  -@bookings.each do |b|
    %tr
      %td
        =b.first_name
      %td
        =b.surname
      %td
        =b.place_of_origin
      %td
        =b.email
      %td
        =b.accept_call
      %td
        =b.phone
      %td
        =b.message
      %td  
        =b.created_at

app/views/admin/enquires.html.haml
%h3
  Total:
  =@entries.size
%table.table.table-striped.table-hover
  %tr
    %th
      first_name
    %th
      email
    %th
      message
    %th
      created at
  -@entries.each do |e|
    %tr
      %td
        =e.first_name
      %td
        =e.email
      %td
        =e.message
      %td  
        =e.created_at

app/views/admin/index.html.haml
%table.table.table-striped.table-hover
  %tr
    %th
      Bookings
    %td
      =@ba
  %tr
    %th
      Enquires
    %td
      =@ea
      

app/views/layouts/Copy of static.html.haml
%html
  %head
    %title= "Yenta"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags 
  %body{"style"=>"background-color: #000;"}
    = render "share/header"
    = image_tag random_background_images, class: "background-image"  
    = yield
    %nav.navbar-fixed-bottom{"role"=>"navigation","style"=>"background-color: transparent;"}
      .foot-static.row            
        = render "share/footer"

app/views/layouts/admin.html.haml
%html
  %head
    %title= "Yenta"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags 
  %body
    = render "admin/header"
    .container
      .starter-template
        = yield

app/views/layouts/application.html.haml
%html
  %head
    %title= "Yenta"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags 
  %body
    = render "share/header"
    = yield
    = render "share/footer"

app/views/layouts/empty.html.haml
%html
  %head
    %title= "Yenta"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags 
  %body
    .empty-wrap
      = yield

app/views/layouts/home.html.haml
%html
  %head
    %title= "Yenta"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags 
  %body{"style"=>"overflow:hidden;"} 
    %nav.navbar-default.navbar-fixed-top{"role"=>"navigation"}
      = render "share/header"
    %nav.navbar.navbar-default.navbar-fixed-bottom{"role"=>"navigation"}
      = yield      
      .foot-static.row
        = render "share/footer"

app/views/layouts/static.html.haml
%html
  %head
    %title= "Yenta"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true     
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags     
    %meta{"name"=>"viewport", "content"=>"width=device-width, initial-scale=1.0"}
    %link{"rel"=>"stylesheet", "href"=>"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"}
    %script{"src"=>"http://code.jquery.com/ui/1.10.3/jquery-ui.js"}
  %body{"style"=>"background-color: #000;"}
    = render "share/header"
    = image_tag random_background_images, class: "background-image"  
    = yield
    %nav.navbar-fixed-bottom{"role"=>"navigation","style"=>"background-color: transparent;"}
      .foot-static.row            
        = render "share/footer"

app/views/share/_cf_error_messages.html.erb
<% if object.errors.any? %>
<div class="alert alert-danger clearfix" id="">
  <ul>
    <% object.errors.each do |key, value| %>
      <li><%=t(key)%> <%= t(value) %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/share/_footer.html.haml
.footer-menu.col-lg-8.col-md-8.footer-links
  %ul.nav
    %li
      ="<a>© 2013 TRAVELYENTA PTY. LTD.</a>".html_safe
    %li
      =link_to "privacy", privacy_path
    %li
      =link_to "copyright", copyright_path
    %li
      =link_to "disclaimer", ""           
.social-links.col-lg-4.col-md-4.footer-links
  %ul.nav
    %li
      =link_to image_tag("wireless.png"),""        
    %li
      =link_to image_tag("linkedin.png"),""
    %li
      =link_to image_tag("facebook.png"),""       
.clear 
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-45813249-1', 'travelyenta.com');
  ga('send', 'pageview');

app/views/share/_header.html.haml
.header-div-static
  .logo-small
    =link_to image_tag("yenta_logo_small.jpg"), "/"
  .contact-head
    %div
      1800 GO YENTA (1800 469 3682)
    %div            
      Skype: travel.yenta
    %div 
      =link_to "bookings@travelyenta.com", "mailto:bookings@travelyenta.com"
            
  .menu.row.menu-static
    .col-lg-1.col-md-1
      =" "  
    .col-lg-2.col-md-2
      -if controller?("home")
        =link_to "Home", "/", class:"active"
      -else
        =link_to "Home", "/"
    .col-lg-2.col-md-2
      -if controller?("static") && action?("wwr")
        =link_to "Who we are", who_we_are_path, class:"active"
      -else
        =link_to "Who we are", who_we_are_path
    .col-lg-2.col-md-2
      -if controller?("static") && action?("wwd")
        =link_to "What we do", what_we_do_path, class:"active"
      -else        
        =link_to "What we do", what_we_do_path
    .col-lg-2.col-md-2
      -if controller?("bookings")
        =link_to "Booking/Enquiry", new_booking_path, class:"active"
      -else
        =link_to "Booking/Enquiry", new_booking_path                
    .col-lg-2.col-md-2
      -if controller?("contact")
        =link_to "Contact Us", contact_us_path, class:"active"
      -else
        =link_to "Contact Us", contact_us_path        
    .col-lg-1.col-md-1
      =" "      
  .clear 

app/views/share/_header_img.html.haml
.header-div
  .logo
    =link_to image_tag("yenta_logo_wb.jpg"), "/"
  .menu
    =link_to image_tag("menu_home_active.jpg"), "" 
    =link_to image_tag("menu_wwr.jpg"), "", {"in" =>  "/assets/menu_wwr_active.jpg", "out" =>  "assets/menu_wwr.jpg"}
    =link_to image_tag("menu_wwd.jpg"), "", {"in" =>  "/assets/menu_wwd_active.jpg", "out" =>  "assets/menu_wwd.jpg"}
    =link_to image_tag("menu_cu.jpg"), "", {"in" =>  "/assets/menu_cu_active.jpg", "out" =>  "assets/menu_cu.jpg"}
  .clear 

app/views/share/_header_static.html.haml
.header-div
  .logo
    =link_to image_tag("yenta_logo_wb.jpg"), "/"
  .menu.row
    .col-lg-2.col-md-1
      =" "  
    .col-lg-2.col-md-2
      =link_to "Home", "/", class:"active"
    .col-lg-2.col-md-2
      =link_to "Who we are", who_we_are_path
    .col-lg-2.col-md-2
      =link_to "What we do", ""
    .col-lg-2.col-md-2
      =link_to "", ""      
    .col-lg-2.col-md-2
      =link_to "Contact Us", ""
    .col-lg-2.col-md-1
      =" "      
  .clear 